[package]
name = "piv-authenticator"
version = "0.0.0-unreleased"
authors = ["Nicolas Stalder <n@stalder.io>"]
edition = "2018"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/solokeys/piv-authenticator"
documentation = "https://docs.rs/piv-authenticator"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apdu-dispatch = { version = "0.1", optional = true }
delog = "0.1.0"
flexiber = { version = "0.1", features = ["derive", "heapless"] }
heapless = "0.7"
hex-literal = "0.3"
interchange = "0.2.0"
iso7816 = "0.1"
serde = { version = "1", default-features = false }
trussed = { git = "https://github.com/trussed-dev/trussed" }
# trussed = { path = "../../../trussed" }
untrusted = "0.7"

[dev-dependencies]
littlefs2 = "0.3.1"
rand_core = { version = "0.6", features = ["getrandom"] }

[features]
default = []
strict-pin = []

log-all = []
log-none = []
log-info = []
log-debug = []
log-warn = []
log-error = []
